baseurl = "https://jefflinmd.com/"
languageCode = "en-us"
title = "林建甫 Jeff Lin"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# yihui https://github.com/yihui/yihui.name/blob/master/config.yaml
paginate = 100
rssLimit = 100
hasCJKLanguage = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"
    faq = "/faq/:year/:month/:day/:slug/"
    rbookbasic = "/rbookbasic/"
    biostbasic = "/biostbasic/"
    bigdata = "/bigdata/"
    clinicaltrial = "/clinicaltrial/"
    catedata = "/catedata/"
    survival = "/survival/"
    regression = "/regression/"
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "R 基礎程式語言"
    url = "/rbookbasic/"
    weight = 3
[[menu.main]]
    name = "生物統計 Biostatistics"
    url = "/biostbasic/"
    weight = 4
[[menu.main]]
    name = "大數據分析 Big Data Analysis"
    url = "/bigdata/"
    weight = 5
[[menu.main]]
    name = "臨床試驗 Clinical Trial"
    url = "/clinicaltrial/"
    weight = 6
[[menu.main]]
    name = "醫學類別資料分析 Categorical Data Analysis"
    url = "/catedata/"
    weight = 7
[[menu.main]]
    name = "存活分析 Survival Analysis"
    url = "/survival/"
    weight = 8
[[menu.main]]
    name = "迴歸分析 Regression Analysis"
    url = "/regression/"
    weight = 9

# [[menu.main]]
#     name = "Categories"
#     url = "/categories/"
#     weight = 3

# [[menu.main]]
#     name = "Tags"
#     url = "/tags/"
#     weight = 4

[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "醫學統計, 生物統計, 臨床試驗, 大數據"
    # footer = "&copy; [Jeff Lin](https://yihui.name) 2017 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"
    footer = "&copy; [Jeff Lin 2019](https://jefflinmd.com/)"

#    description = "A Hugo theme ported from the static site generator Ivy."
#    footer = "&copy; [Yihui Xie](https://yihui.name) 2017 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
